"""Add encryption support

Revision ID: b07e8f3c35cf
Revises: e8f95c844ef0
Create Date: 2025-01-29 08:50:15.145964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b07e8f3c35cf'
down_revision = 'e8f95c844ef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('encryption_salt', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.drop_column('encryption_salt')
        batch_op.drop_column('encrypted')

    # ### end Alembic commands ###
